### ISSUE TITLE
Lint on fly does not work 

### ISSUE THREAD

**Issue by ryncops** [hebaishi/linter-gcc#15]
Hello!
I've been trying for a while , without success, to make linter-gcc lint on the fly, not only on save. Is it not a possible feature at this moment? It works fine at file save, but not on the fly. The python linter-flake8 , for example  works on the fly. But not the gcc version, nor the javac one but that's another issue.

**Comment by hebaishi** [comment]
Hello. The reason linter-gcc doesn't lint on-the-fly is because linting is achieved by compilation. Compiling a large C/C++ source file can be time consuming and linting on-the-fly would make the package unresponsive while it waits for source the file to compile. That is why linting on-the-fly has been disabled.

**Comment by ryncops** [comment]
I understand. Thank you for your reply!
