### ISSUE TITLE
uintXX_t does not name a type in header files

### ISSUE THREAD

**Issue by jmscaramal** [hebaishi/linter-gcc#50]
Hello... I'm not sure if it is really an issue, however I couldn't find the answer in any other place. 

I'm trying to use atom for coding my C projects (moving from eclipse). I've recently installed atom and platformio-ide packages (which includes linter-gcc, clang-autocomplete,etc) and it is all perfectly working (including my .gcc-flags.json file). However, an issue raised up:

Usually I don't put any header file (#include statements)  in my header files. When am I dealing with some type from stdint.h (uint8_t for example), I just make sure that in my source file, the stdint.h file is being included before my header file. So, in atom, when I put some uintxx_t in my header file, the linter-gcc accuses an error: **'uint8_t' does not name a type.**

So, having said that, can I remove these errors WITHOUT including the stdint.h in my header file? I'm sorry if it is a newbie question, but I've googled it for some time and I couldn't find any related issue.

**Comment by hebaishi** [comment]
The `uintxx` types are defined in `stdint.h` so you cannot use them without the header file, unless you define them yourself. I don't recommend you do this, however. If something is part of a standard header, you should just use the header instead of defining bits and pieces.

Also, there is no problem having `#include` statements in your own header file. Defining/declaring **everything** yourself is not practical, so you often **need** to include other headers into your header file. You can simply use header guards to make sure your header files are not included twice. You can read more about include guards [here](https://en.wikipedia.org/wiki/Include_guard). Also, you need not worry about standard headers being included twice because they all have include guards. Does that answer your question?

**Comment by jmscaramal** [comment]
Hello @hebaishi . Thanks for answering. More or less. 

Actually, I'm aware of include guards and the recommendations of including other header files in my own one. This is just part of a standard design for embedded programming. 
My program works fine, it compiles normally in this way (no #include in header files, and appropriate #include order in source file). I was just wondering if it is possible to make the linter "to understand" that the include for such datatype is in the corresponding source file. 

Anyway, thank you so much for your attention and answering...

**Comment by arpemar98** [comment]
Hello, excuse me.
I have a problem with Linter.gcc, show me:

linter-gcc: Executable not found
"/usr/bin/g++" not found

I read the guid, but I do not understand very well the part of installing the packages, and when I use the cygwin with the command, it shows me /usr/bin/gcc.

I do not know how to fix it
