### ISSUE TITLE
How to ignore the error info `No such file or directory`?

### ISSUE THREAD

**Issue by Lw-Cui** [hebaishi/linter-gcc#68]
## Checklist
* [x] Check that you have the GNU C Compiler installed by typing ```gcc --version``` into a terminal.
* [x] If you don't have the ```linter``` package installed, either update to the latest version of ```linter-gcc``` or install linter directly with ```apm install linter```.
* [x] Ensure that you are using a valid grammar - either C/C++/C++14

## Issue (including debugging messages):
Hello, thanks for your plugin first.
I would like to know how to ignore the error info `No such file or directory`. Because I use `CMake`, which specifies the include path, the error info is unnecessary and annoying. 
Could I ignore the error info?

**Comment by hebaishi** [comment]
I do not think you understand the problem here. This error comes up because the compiler **cannot** find one of your files, and therefore **cannot continue** with compilation. If you want to ignore this error, simply disable linter-gcc. Otherwise, I suggest you add the include path(s) from your `CMakeLists.txt` configuration file to the list of linter-gcc include paths.

**Comment by Lw-Cui** [comment]
Thanks!

**Comment by sompylasar** [comment]
Related: https://github.com/hebaishi/linter-gcc/issues/124
